// Buyer Features Service
export const buyerFeaturesService = {
  async fetchFeatureData(featureName: string) {
    try {
      const response = await fetch(`/api/buyer/features/${featureName}`);
      return await response.json();
    } catch (error) {
      console.error(`Error fetching ${featureName}:`, error);
      return null;
    }
  }
};

// Premium Sub-Features for Smart Sourcing, My Reputation, and Supplier Insights
export const premiumSubFeatures = {
  smartSourcing: [
    {
      id: "ai-supplier-match",
      name: "AI Supplier Matching",
      description: "Intelligent algorithm matches your requirements with best suppliers",
      icon: "Zap",
      category: "Smart Sourcing",
      premium: true,
    },
    {
      id: "bulk-negotiation",
      name: "Bulk Negotiation Engine",
      description: "Automated price negotiation for bulk orders with real-time analytics",
      icon: "Percent",
      category: "Smart Sourcing",
      premium: true,
    },
    {
      id: "supplier-comparison",
      name: "Advanced Supplier Comparison",
      description: "Side-by-side comparison with quality, price, and delivery metrics",
      icon: "BarChart3",
      category: "Smart Sourcing",
      premium: true,
    },
    {
      id: "price-optimization",
      name: "Dynamic Price Optimization",
      description: "Real-time price tracking and optimization recommendations",
      icon: "TrendingDown",
      category: "Smart Sourcing",
      premium: true,
    },
  ],
  myReputation: [
    {
      id: "reputation-score",
      name: "Dynamic Reputation Score",
      description: "Real-time reputation tracking with detailed performance breakdown",
      icon: "TrendingUp",
      category: "My Reputation",
      premium: true,
    },
    {
      id: "review-management",
      name: "Review Management Hub",
      description: "Manage, respond to, and analyze all supplier reviews in one place",
      icon: "MessageSquare",
      category: "My Reputation",
      premium: true,
    },
    {
      id: "trust-badges",
      name: "Earned Trust Badges",
      description: "Unlock premium badges based on transaction history and ratings",
      icon: "Award",
      category: "My Reputation",
      premium: true,
    },
    {
      id: "reputation-alerts",
      name: "Reputation Alert System",
      description: "Get notified of reputation changes and review responses in real-time",
      icon: "Bell",
      category: "My Reputation",
      premium: true,
    },
    {
      id: "sentiment-analysis",
      name: "AI Sentiment Analysis",
      description: "Advanced sentiment tracking across all reviews with emotion detection",
      icon: "Brain",
      category: "My Reputation",
      premium: true,
    },
    {
      id: "reputation-timeline",
      name: "Reputation Timeline",
      description: "Visual timeline showing your reputation journey and key milestones",
      icon: "Clock",
      category: "My Reputation",
      premium: true,
    },
    {
      id: "competitor-benchmarking",
      name: "Competitor Benchmarking",
      description: "Compare your reputation metrics against industry averages",
      icon: "Target",
      category: "My Reputation",
      premium: true,
    },
    {
      id: "response-templates",
      name: "Smart Response Templates",
      description: "AI-generated response templates for different review scenarios",
      icon: "FileText",
      category: "My Reputation",
      premium: true,
    },
    {
      id: "reputation-boost",
      name: "Reputation Boost Insights",
      description: "Personalized recommendations to improve your reputation score",
      icon: "Rocket",
      category: "My Reputation",
      premium: true,
    },
    {
      id: "verified-transactions",
      name: "Verified Transaction History",
      description: "Blockchain-verified transaction records for enhanced credibility",
      icon: "Shield",
      category: "My Reputation",
      premium: true,
    },
    {
      id: "reputation-analytics",
      name: "Advanced Analytics Dashboard",
      description: "Deep-dive analytics with charts, trends, and predictive insights",
      icon: "BarChart3",
      category: "My Reputation",
      premium: true,
    },
    {
      id: "social-proof",
      name: "Social Proof Widgets",
      description: "Embeddable reputation widgets to showcase on external platforms",
      icon: "Share2",
      category: "My Reputation",
      premium: true,
    },
    {
      id: "reputation-insurance",
      name: "Reputation Protection",
      description: "Fraud detection and dispute resolution to protect your reputation",
      icon: "Lock",
      category: "My Reputation",
      premium: true,
    },
    {
      id: "performance-leaderboard",
      name: "Performance Leaderboard",
      description: "See where you rank among top buyers in your region and category",
      icon: "Trophy",
      category: "My Reputation",
      premium: true,
    },
  ],
  supplierInsights: [
    {
      id: "predictive-analytics",
      name: "Predictive Performance Analytics",
      description: "AI-powered forecasting of supplier performance and reliability",
      icon: "Brain",
      category: "Supplier Insights",
      premium: true,
    },
    {
      id: "market-intelligence",
      name: "Market Intelligence Reports",
      description: "Comprehensive market trends and supplier benchmarking data",
      icon: "Globe",
      category: "Supplier Insights",
      premium: true,
    },
    {
      id: "risk-assessment",
      name: "Supplier Risk Assessment",
      description: "Automated risk scoring with compliance and financial health checks",
      icon: "AlertTriangle",
      category: "Supplier Insights",
      premium: true,
    },
    {
      id: "supplier-network",
      name: "Supplier Network Analysis",
      description: "Visualize supplier relationships and supply chain dependencies",
      icon: "Network",
      category: "Supplier Insights",
      premium: true,
    },
    {
      id: "quality-tracker",
      name: "Quality Consistency Tracker",
      description: "Monitor quality trends and consistency across all deliveries",
      icon: "CheckCircle",
      category: "Supplier Insights",
      premium: true,
    },
    {
      id: "delivery-reliability",
      name: "Delivery Reliability Score",
      description: "Track on-time delivery rates and predict future reliability",
      icon: "Clock",
      category: "Supplier Insights",
      premium: true,
    },
    {
      id: "price-competitiveness",
      name: "Price Competitiveness Analysis",
      description: "Compare supplier pricing against market averages in real-time",
      icon: "TrendingDown",
      category: "Supplier Insights",
      premium: true,
    },
    {
      id: "communication-metrics",
      name: "Communication Response Metrics",
      description: "Analyze supplier response times and communication quality",
      icon: "MessageCircle",
      category: "Supplier Insights",
      premium: true,
    },
    {
      id: "availability-forecast",
      name: "Product Availability Forecast",
      description: "Predict stock availability and restock timelines",
      icon: "Package",
      category: "Supplier Insights",
      premium: true,
    },
    {
      id: "trust-verification",
      name: "Trust & Verification Status",
      description: "Blockchain-verified credentials and certification tracking",
      icon: "ShieldCheck",
      category: "Supplier Insights",
      premium: true,
    },
    {
      id: "supplier-comparison",
      name: "Multi-Supplier Comparison",
      description: "Side-by-side comparison of multiple suppliers across all metrics",
      icon: "BarChart2",
      category: "Supplier Insights",
      premium: true,
    },
    {
      id: "smart-recommendations",
      name: "AI Smart Recommendations",
      description: "Get personalized supplier recommendations based on your needs",
      icon: "Sparkles",
      category: "Supplier Insights",
      premium: true,
    },
    {
      id: "performance-alerts",
      name: "Performance Alert System",
      description: "Real-time alerts for supplier performance changes and issues",
      icon: "Bell",
      category: "Supplier Insights",
      premium: true,
    },
    {
      id: "historical-analytics",
      name: "Historical Performance Analytics",
      description: "Deep-dive into historical data with trend analysis and patterns",
      icon: "LineChart",
      category: "Supplier Insights",
      premium: true,
    },
  ],
  negotiationHub: [
    {
      id: "ai-counter-offer",
      name: "AI Counter-Offer Engine",
      description: "Smart AI-powered counter-offer suggestions based on market data",
      icon: "Brain",
      category: "Negotiation Hub",
      premium: true,
    },
    {
      id: "realtime-chat",
      name: "Real-Time Negotiation Chat",
      description: "Live chat with suppliers with offer tracking and history",
      icon: "MessageCircle",
      category: "Negotiation Hub",
      premium: true,
    },
    {
      id: "multi-party",
      name: "Multi-Party Negotiation Room",
      description: "Negotiate with multiple suppliers simultaneously",
      icon: "Users",
      category: "Negotiation Hub",
      premium: true,
    },
    {
      id: "smart-contracts",
      name: "Smart Contract Auto-Generation",
      description: "Automatically generate legal contracts from negotiation terms",
      icon: "FileText",
      category: "Negotiation Hub",
      premium: true,
    },
    {
      id: "price-history",
      name: "Price History Analytics",
      description: "Historical price trends and predictive analytics",
      icon: "LineChart",
      category: "Negotiation Hub",
      premium: true,
    },
    {
      id: "auto-bot",
      name: "Automated Negotiation Bot",
      description: "AI bot that negotiates on your behalf with custom strategies",
      icon: "Bot",
      category: "Negotiation Hub",
      premium: true,
    },
    {
      id: "sentiment-analysis",
      name: "Sentiment Analysis Dashboard",
      description: "Real-time sentiment tracking during negotiations",
      icon: "Heart",
      category: "Negotiation Hub",
      premium: true,
    },
    {
      id: "deadline-tracker",
      name: "Deadline & Urgency Tracker",
      description: "Track negotiation deadlines with smart alerts",
      icon: "Clock",
      category: "Negotiation Hub",
      premium: true,
    },
    {
      id: "templates-library",
      name: "Negotiation Templates Library",
      description: "Pre-built negotiation strategies for different scenarios",
      icon: "BookOpen",
      category: "Negotiation Hub",
      premium: true,
    },
    {
      id: "performance-metrics",
      name: "Performance Metrics & Win Rate",
      description: "Track your negotiation success rate and savings",
      icon: "TrendingUp",
      category: "Negotiation Hub",
      premium: true,
    },
  ],
};
