import {
  LayoutDashboard,
  Package,
  Gavel,
  Truck,
  Search,
  UserCircle,
  CreditCard,
  Target,
  MessageSquare,
  TrendingUp,
  Map,
  ShoppingBag,
  ShieldCheck,
  Zap,
  Lock,
  BarChart3,
  Users,
  Award,
  Sparkles,
  PieChart,
  Link2,
  Table as TableIcon,
  Sprout,
  Shield,
  DollarSign,
  ShieldAlert
} from "lucide-react";

export const farmerNav = [
  { label: "Farm Insights", href: "/farmer/dashboard", icon: BarChart3, section: "Overview" },
  { label: "Smart Product Hub", href: "/farmer/dashboard", icon: Package, section: "Inventory" },
  { label: "Trust & Identity", href: "/farmer/dashboard", icon: ShieldCheck, section: "Reputation" },
  { label: "AgriPay Center", href: "/farmer/dashboard", icon: CreditCard, section: "Payments" },
  { label: "Order Control", href: "/farmer/dashboard", icon: ShoppingBag, section: "Orders" },
  { label: "Tender Bids", href: "/farmer/dashboard", icon: Gavel, section: "Tenders" },
  { label: "Logistics Manager", href: "/farmer/dashboard", icon: Truck, section: "Logistics" },
  { label: "Crop Advisor", href: "/farmer/dashboard", icon: Sprout, section: "Advisor" },
  { label: "AI Quality Shield", href: "/farmer/dashboard", icon: ShieldCheck, section: "Quality" },
  { label: "AgriChat", href: "/farmer/dashboard", icon: MessageSquare, section: "Chat" },
  { label: "Agri-Intelligence", href: "/farmer/dashboard", icon: Sparkles, section: "AI Insights" },
  { label: "AI Price Advisor", href: "/farmer/dashboard", icon: TrendingUp, section: "Analytics" },
  { label: "Price Protection", href: "/farmer/dashboard", icon: ShieldCheck, section: "Finance" },
  { label: "Auto-Sell Rules", href: "/farmer/dashboard", icon: Zap, section: "Smart Trading" },
  { label: "Behavioral Insights", href: "/farmer/dashboard", icon: Target, section: "Behavioral" },
  { label: "Blockchain Trace", href: "/farmer/dashboard", icon: Shield, section: "Blockchain" },
  { label: "Escrow Payments", href: "/farmer/dashboard", icon: DollarSign, section: "Escrow" },
];

export const buyerNav = [
  { label: "Cockpit", href: "/buyer/dashboard", icon: LayoutDashboard, section: "Overview" },
  { label: "AI Procurement", href: "/buyer/dashboard", icon: Sparkles, section: "Procurement" },
  { label: "Smart Sourcing", href: "/buyer/search", icon: Search, section: "Sourcing Space" },
  { label: "My Reputation", href: "/buyer/dashboard", icon: ShieldCheck, section: "Reputation" },
  { label: "Supplier Insights", href: "/buyer/dashboard", icon: Users, section: "Suppliers" },
  { label: "Trust & Reviews", href: "/buyer/dashboard", icon: ShieldCheck, section: "Reviews" },
  { label: "Price Intelligence", href: "/buyer/dashboard", icon: BarChart3, section: "Intelligence" },
  { label: "Safe-Lock Hub", href: "/buyer/dashboard", icon: Lock, section: "Pre-Booking" },
  { label: "Negotiation Hub", href: "/buyer/dashboard", icon: Gavel, section: "Bidding" },
  { label: "Agri-Intelligence", href: "/buyer/dashboard", icon: Sparkles, section: "AI Insights" },
  { label: "AgriChat", href: "/buyer/dashboard", icon: MessageSquare, section: "Chat" },
  { label: "Order Tracker", href: "/buyer/dashboard", icon: ShoppingBag, section: "Tracking" },
  { label: "TraceChain", href: "/buyer/dashboard", icon: Link2, section: "Traceability" },
  { label: "Blockchain Trace", href: "/buyer/dashboard", icon: Shield, section: "Blockchain" },
  { label: "Escrow Payments", href: "/buyer/dashboard", icon: DollarSign, section: "Escrow" },
  { label: "Security Hub", href: "/buyer/dashboard", icon: ShieldAlert, section: "Security" },
  { label: "Bulk Trade Desk", href: "/buyer/dashboard", icon: TableIcon, section: "Bulk Trade" },
];
